### ISSUE TITLE
よい電卓です。

### ISSUE THREAD

**Issue by c0a2104665** [C0A21122/ProjExD#12]
https://github.com/C0A21122/ProjExD/blob/246a5e90912711b57c2dba45faff690f9687721b/ex02/calc.py#L38
コメントで詳しく説明があると良いと思いました。

**Comment by C0A21122** [comment]
> https://github.com/C0A21122/ProjExD/blob/246a5e90912711b57c2dba45faff690f9687721b/ex02/calc.py#L38
> 
> コメントで詳しく説明があると良いと思いました。

修正しました。
