### ISSUE TITLE
リスタート

### ISSUE THREAD

**Issue by c0a21148** [C0A21122/ProjExD#14]
https://github.com/C0A21122/ProjExD/blob/2a529eed0230194a01ea461782e57bd72801cee5/ex03/maze.py#L11
迷路を再生成する機能は面白いと思いました。こうかとんが消えないならもっといいと思いました。

**Comment by C0A21122** [comment]
> https://github.com/C0A21122/ProjExD/blob/2a529eed0230194a01ea461782e57bd72801cee5/ex03/maze.py#L11
> 
> 迷路を再生成する機能は面白いと思いました。こうかとんが消えないならもっといいと思いました。

修正します。ありがとうございます。
