### ISSUE TITLE
とても見やすいです。

### ISSUE THREAD

**Issue by c0a2104665** [C0A21122/ProjExD#17]
https://github.com/C0A21122/ProjExD/blob/ebfb12440f116f46312545d8dbc34caf3a0a3957/ex03/maze.py#L24
コメントされていてとても見やすくコードが書かれていてよかったです。

**Comment by C0A21122** [comment]
> https://github.com/C0A21122/ProjExD/blob/ebfb12440f116f46312545d8dbc34caf3a0a3957/ex03/maze.py#L24
> 
> コメントされていてとても見やすくコードが書かれていてよかったです。

ありがとうございます。
